SimVascular/SimVascular

BuildWithMake/MakeHelpers/mpich.x64_linux.mk
BuildWithMake/MakeHelpers/mpich2.usr.local.x64_linux.mk
BuildWithMake/MakeHelpers/mpich2.usr.x64_linux.mk
BuildWithMake/MakeHelpers/openmpi.x64_linux.mk
BuildWithMake/include.mk

added new variables to makefile build:
MAKE_WITH_OPENMPI
MAKE_WITH_MPICH
which are mutually exclusive
the default is now "MAKE_WITH_OPENMPI=1"
these call scripts that attempt to autodetect the compiler flags for mpi

updating make build to default to openmpi

---

Code/Source/Mesh/MeshObject/cv_mesh_init.cxx
Tcl/SimVascular_2.0/Plugins/tetgen.tcl

Fixes error in Windows for crashing when values flag isn't sent in with SetMeshOptions

BUG: Made SetMeshOptions value argument required to avoid crashing

---

Tcl/SimVascular_2.0/GUI/model.tcl

If a polydata is loaded without a corresponding .facenames file, but the array modelfaceid exists on the solid, the faces are loaded and given a noname_id name

DEV: Added modelfaceid check for polydata load

---

Tcl/SimVascular_2.0/GUI/model.tcl

If a polydata is loaded without a corresponding .facenames file, but the array modelfaceid exists on the solid, the faces are loaded and given a noname_id name

Made it possible to load polydata with ModelFaceID but no facenames file

---

Code/Source/Model/SolidModel/cvSolidModel.cxx
Tcl/SimVascular_2.0/GUI/gui.tcl
Tcl/SimVascular_2.0/GUI/model.tcl
Tcl/SimVascular_2.0/simvascular_startup.tcl

-Sets max width and height to screen width and height
-Sets initial size to slightly smaller than screen width and height
-Makes window transparent until it loads and splash screen exits
-Sets sashpos relative to the current window size
-Doesn't add model kernels to treeview unless they are available

Fix startup

---

Code/CMake/FindOPENCASCADE.cmake

static link order needs to be a certain way with gcc

Fixed static library link order for occt with gcc

---

Code/SuperBuild/OPENCASCADE.cmake

Pointing now to tag of occt repo so that we can get rid of 7.0 specific repo

commited revision number for opencascade repo

---

Code/Scripts/CMakeLists.txt

A couple lines added to mysim startup with the downloadable tcl, tk. Otherwise, the libraries cannot be found.

Mac needs link paths for tcl, tk libs

---

BuildWithMake/Makefile
BuildWithMake/include.mk
Code/FlowSolvers/ThreeDSolver/SolverIO/Makefile
Code/FlowSolvers/ThreeDSolver/svPost/Makefile
Code/FlowSolvers/ThreeDSolver/svPre/Makefile
Code/FlowSolvers/ThreeDSolver/svSolver/Makefile

when building use make, it creates *.h files that confuse
cmake build.  Moved autogenerated *.h files into subdirectories
outside the view of cmake.

fixed bug causing cmake to fail after building with make

---

Code/Source/Common/Utils/cv_utils_init.cxx
Code/Source/TclPython/cv_pythoninterp_init.cxx

all Tcl init functions must return a value (TCL_OK or TCL_ERROR)

*_init functions must return a value

---

BuildWithMake/include.mk
Code/Source/Modules/Mesh/Makefile
Code/Source/Modules/Model/Makefile
Code/Source/Modules/Model/svModelElementOCCT.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/Makefile
Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/Makefile
Code/ThirdParty/vmtk/Makefile
Tcl/SimVascular_2.0/Plugins/tclpython.tcl

BUILD: fixed makefiles to add opencascade for new gui
BUG: fixed missing return in function in svModelElementOCCT.cxx
BUG: catching error in old gui when you something goes wrong when initializing pythontcl

2017-01-04-final-update-for-2016

---

Code/Source/Common/Geometry/cv_sys_geom.cxx
Code/Source/Mesh/MMGMeshUtils/cv_mmg_mesh_utils.cxx
Code/Source/Modules/Model/svModelUtils.cxx

If using normals filter, turn off point normals otherwise visualization looks weird
Also make sure splitting is off so that duplicate points are not used in operation such as remeshing

DEV: Edit polydata normals filters

---

BuildWithMake/Release/Makefile
Tcl/SimVascular_2.0/GUI/gui.tcl
Tcl/SimVascular_2.0/simvascular_startup.tcl

DEV: updated Windows registry to use new names of external executables (e.g. svsolver), also now can call either the nompi or mpi version of svsolver

2017-01-13-use-svsolver-registry

---

BuildWithMake/Release/Makefile

BUG: two line change to not copy mitk libs to toplevel install directory for Windows

2017-01-30-change-for-win32-install-for-makeb-build

---

Code/CMake/SimVascularDependentOptions.cmake
Code/CMake/SimVascularMacros.cmake
Code/CMake/SimVascularOptions.cmake
Code/Source/Common/Geometry/cv_geom_init.cxx
Code/Source/Common/Geometry/cv_sys_geom.cxx
Code/Source/Common/Geometry/cv_sys_geom.h
Code/Source/Model/OCCTSolidModel/cvOCCTSolidModel.cxx
Code/Source/Model/OCCTSolidModel/cv_occt_init.cxx
Code/Source/Modules/Model/svModelElement.h
Code/Source/Modules/Model/svModelUtils.cxx
Code/Source/Modules/Model/svModelUtils.h
Code/Source/Plugins/org.sv.gui.qt.modeling/files.cmake
Code/Source/Plugins/org.sv.gui.qt.modeling/plugin.xml
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelPreferencePage.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelPreferencePage.h
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelPreferencePage.ui
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelingPluginActivator.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svSegSelectionWidget.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svSegSelectionWidget.h
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svSegSelectionWidget.ui
Code/Source/vtkSV/Modules/NURBS/vtkSVControlGrid.cxx
Code/Source/vtkSV/Modules/NURBS/vtkSVLoftNURBSSurface.cxx
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSCurve.cxx
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSCurve.h
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSSurface.cxx
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSSurface.h
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSUtils.cxx
Code/Source/vtkSV/Modules/NURBS/vtkSVNURBSUtils.h

DEV: Adds nurbs lofting to OpenCASCADE and preferences page
A model preferences page was created containing the lofting preferences for NURBS.
The nurbs lofting is now available under the PolyData and OpenCASCADE modeling by selecting advanced lofting in the select segmentation window pane. The name can be changed if people don't like "advanced". Can also be made default lofting after testing.

2017 03 29 nurbs lofting

---

Tcl/SimVascular_2.0/simvascular_startup.tcl

The old gui now properly picks up the latest version of the svsolver installed on the system by default.

DEV: fixed harded code path for svsolver in tcl gui

---

Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.cxx
Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.h
Code/Source/Mesh/TetGenMeshObject/cv_tetgenmesh_utils.cxx
Code/Source/Mesh/TetGenMeshObject/cv_tetgenmesh_utils.h
Code/Source/Model/PolyDataSolidModel/vtkGetBoundaryFaces.cxx
Code/Source/Modules/Mesh/Common/svMeshTetGen.cxx
Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.cxx
Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.h
Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.ui

Implements meshing for holes and subdomains using tetgen.
Right now, the most basic way of incorporating both of these features is implemented. A 3d coordinate is given to indicate a hole or subdomain lying strictly within a surface. Input surfaces with more than one connected region and non-manifold edges are now allowed for these types of meshes.

2017 6 29 tetgen multidomain

---

Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.cxx
Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.h
Code/Source/Mesh/VMTKUtils/cv_vmtk_utils.cxx
Code/Source/Mesh/VMTKUtils/cv_vmtk_utils.h
Code/Source/Modules/Mesh/Common/svMeshTetGen.cxx
Code/Source/Modules/Model/Common/svModelUtils.cxx
Code/Source/Modules/Model/Common/svModelUtils.h
Code/Source/Plugins/org.sv.gui.qt.datamanager/src/internal/svQmitkDataManagerView.h
Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.cxx
Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.ui
Code/Source/Plugins/org.sv.gui.qt.modeling/files.cmake
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svCapSelectionWidget.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svCapSelectionWidget.h
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svCapSelectionWidget.ui
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.h
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.ui
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelExtractPathsAction.cxx
Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelExtractPathsAction.h

DEV: Updates to centerline extraction in modeling and meshing
Creates a plugin button to extract centerlines and specify source and target caps.
Also, implements variable boundary layer thickness, which is especially effective when doing radius-based meshing.

2017 11 21 centerlines updates

---

Code/Source/sv/Mesh/TetGenMeshObject/sv_TetGenMeshObject.cxx
Code/Source/sv/Mesh/TetGenMeshObject/sv_TetGenMeshObject.h
Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx
Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.h
Code/Source/sv4gui/Modules/Mesh/Common/sv4gui_MeshTetGen.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.meshing/sv4gui_MeshEdit.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.meshing/sv4gui_MeshEdit.ui

Makes it possible to extrude the boundary layer either inward or outward.
Also makes it possible to label the boundary layer with different ModelRegionID.
Additionally updates boundary layer meshing to use mmg for original surface remeshing rather than vmtk.

2018 06 12 try bl as multi domain

---

Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIJob.cxx
Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIeqClass.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/plugin.xml
Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui

removed the old 3d segmentation icon. However users will see an error if they double click a 3d segmentation in the datamanager now.

Remove 3d seg

---

Code/Scripts/executable/install/simvascular-macos.in
Code/Source/sv4gui/Modules/Mesh/Common/sv4gui_MeshLegacyIO.cxx

When meshing a boundary layer for FSI the volume meshes for both the fluid and solid regions were being written out as surface meshes.

Fix for volume mesh not being written.

---

.gitignore
Code/CMake/SimVascularUseExternals.cmake
Externals/CMake/SvExtVersions.cmake

Custom plugins use CMake files a bit differently than the usual sv when building. External versions were hard coded in SimVascularUseExternals.cmake. 
There are two places where external version numbers (e.g. mitk version . number) are specified in the CMake file so we should really restructured them someone to set them in a single place.
Plugins will need to set the externals version number in their CMakeLists.txt file 
set(SV_EXTERNALS_VERSION_NUMBER "2018.05" CACHE STRING "SimVascular Externals Release Version")

Add external versions needed by plugins.

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.application/resources/simvascular.qss

Added explicitly setting color for QMenuBar and QMenu::item in the simvascular.qss file.

Fix for too light menubar and popup menu items font color. Issue #379.

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx

While testing a fresh multi-processor simulation I found a problem checking for the **N-procs_case** directory.

Add fix for multi-processor case.

---

Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx

Centerlines were not being computed correctly. The problem was caused by incorrect array addressing while copying source and target IDs.

Fix incorrect array addressing.

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.ui

Chagnes we discussed in sv call. Tab orders are switched and networks are only loaded when the segmentation button is clicked.

changing ml tab orders and only loading networks on button press

---

Code/Source/sv3/Segmentation/sv3_Contour.cxx
Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourGroupIO.cxx

The contour center is used when calculating contour area but the contour center was not being calculated when contour groups are read in.

Fix for not calculating contour center when reading contour groups.

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.ui

This is a problem when a 2D Segmentation plugin is opened when a contour group is not defined, for example when SV opens and shows the last active plugin.

Lofting parameters button crashes sv 521

---

Python/site-packages/sv_ml/sv_wrapper.py

This fixed the machine learning code crashing on Ubuntu.
The environment command is needed to ensure tensorflow doesnt look for GPUs, which won't work unless CUDA is properly configured. With the environment setting it only uses CPU which should work for most people.
It used to be there, not sure how it disappeared, but I added it back.

missing environment variable in sv_wrapper sv_ml python script

---

Code/Source/sv4gui/Modules/Model/Common/sv4gui_ModelVtkMapper3D.cxx
Code/Source/sv4gui/Modules/Model/Common/sv4gui_ModelVtkMapper3D.h

This is a fix for viewing models that contain a large number of faces. The SV mapper code was creating new vtk mappers and actors for each face every time the view was updated (e.g. rotating the view with the mouse).

Viewing large geometries slow 640

---

Code/Source/PythonAPI/ModelingModel_PyClass.cxx
Code/Source/PythonAPI/ModelingPolyData_PyClass.cxx

This `compute_boundary_faces()` method  was defined for all Model classes but Parasolid and OpenCasade models don't need it and was not implemented in SV for these kernel types and was returning an error.

Redefine the compute_boundary_faces() method for just PolyData models.

---

BuildWithMake/MakeHelpers/2019.06/compiler.vs19.16.x64_cygwin.mk
Code/Source/PythonAPI/CMakeLists.txt

BUG: fixed bug in CMake build for PythonAPI (missing US_MODULE_NAME)
BUILD: commented out a few compile and link flags on windows for less verbose output by default

2021-04-20 Bug Fix for CMake on Windows in PythonAPI

---

.gitmodules
CMakeLists.txt

Closes #853. Note the relative paths in ```.gitmodules``` to keep the same access method as in the parent repository.
See for reference: https://cliutils.gitlab.io/modern-cmake/chapters/projects/submodule.html

Add svZeroDSolver (#853)

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferences.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx

svSolver is now built using OpenMPI so the `Simulation` tool should now check that OpenMPI is installed.

Change to look for OpenMPI rather than MPICH for svsolver MPI.

---

Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.cxx

SV currently renames a project's `Simulations1d` directory to `ROMSimulations` but for old SV projects there is no `Simulations1d` directory. Add creating the `ROMSimulations` if there is no `Simulations1d` directory.

Add creating a ROMSimulations dir if a Simulations1d dir is not present.

---

Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx

This fixes the `sv4guiSeg2DEdit::initialize()` code that was reading in a `.svproj` file to get the project image name for ML.

Add code to set/get image file path from the mitk image node.

---

Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/Makefile
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/files.cmake
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ConvertProcessHandlerROM.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ConvertProcessHandlerROM.h
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ConvertWorkerROM.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ConvertWorkerROM.h
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.h
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.cxx
Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.h
Python/site-packages/sv_rom_extract_results/extract_results.py
Python/site-packages/sv_rom_extract_results/manage.py
Python/site-packages/sv_rom_extract_results/solver.py

These updates implement the execution of the Python `sv_rom_extract_results/extract_results.py` script to convert ROM simulation results. `QThreads` are used to execute the script so it doesn't freeze the SV GUI. 
@osmsc These changes need to be tested on Windows, some not very clear documentation about using `QThreads`.

Rom convert results freezes sv 912

---

Code/Source/sv4gui/Plugins/org.sv.pythondatanodes/Dmg_PyModule.cxx

The Python API dmg.add_model() method is used to add a model to SV. A model node is correctly added to the SV Data Manager but no model faces are added to the Model Tool GUI panel. Add computing faces so they appear in the GUI.

Add faces so they appear in the GUI.
