SimVascular/SimVascular

- .travis.yml
- Code/CMake/SimVascularInstallLibs.cmake
- travis/travis_before_script_cleanup.sh
- travis/travis_build_and_test.sh
- travis/travis_build_itk.sh
- travis/travis_build_vtk.sh
- travis/travis_build_vtk_itk.sh
This PR adds minimal travis ci support.  Build are done only on linux, and testing is not performed.
> Add travis ci support

- .travis.yml
Very simple PR, can be merged quickly.
> add tklib to travis, since it has been whitelisted

- Code/ThirdParty/metis/simvascular_metis/Lib/CMakeLists.txt
This is a simple change that can be merge quickly.
> remove metis message from thirdparty

- Code/Source/Mesh/MeshSimAdapt/cvMeshSimAdapt.cxx
- Code/Source/Mesh/MeshSimMeshObject/cvMeshSimMeshObject.cxx
Faces werent being written correctly. Needed to add InitTraversal at end of Adapt step.
> BUG: Fixed writing of seperate mesh faces in meshsim mesher

- Code/Source/Mesh/AdaptObject/cvAdaptObject.h
- Code/Source/Mesh/AdaptObject/cv_adapt_init.cxx
- Code/Source/Mesh/AdaptObject/cv_adapt_utils.cxx
- Code/Source/Mesh/MeshSimAdapt/cvMeshSimAdapt.cxx
- Code/Source/Mesh/MeshSimAdapt/cvMeshSimAdapt.h
- Code/Source/Mesh/TetGenAdapt/cvTetGenAdapt.cxx
- Code/Source/Mesh/TetGenAdapt/cvTetGenAdapt.h
new post solver outputs average speed instead of ybar. Changed adaptor code accordingly
> DEV: Changed adaptor to work with average speed instead of ybar array

- Code/SuperBuild/ITK.cmake
- Code/SuperBuild/VTK.cmake
Updated make for vtk6.2 and itk4.8
> DEV: Updated superbuild cmake to vtk 6.2 and itk 4.8

- Code/Source/Common/Geometry/cv_sys_geom.cxx
- Tcl/SimVascular_2.0/GUI/gui.tcl
- Tcl/SimVascular_2.0/GUI/sv-gui-common.tcl
Change to vtkOBBTree for line intersection code in bc.
> Bcproblems

- Code/FlowSolvers/ThreeDSolver/svPost/post_solver.cxx
- Code/Source/Mesh/AdaptObject/cvAdaptObject.h
- Code/Source/Mesh/AdaptObject/cv_adapt_init.cxx
- Code/Source/Mesh/AdaptObject/cv_adapt_utils.cxx
- Code/Source/Mesh/AdaptObject/cv_adapt_utils.h
- Code/Source/Mesh/MeshSimAdapt/cvMeshSimAdapt.cxx
- Code/Source/Mesh/MeshSimAdapt/cvMeshSimAdapt.h
- Code/Source/Mesh/TetGenAdapt/cvTetGenAdapt.cxx
- Code/Source/Mesh/TetGenAdapt/cvTetGenAdapt.h
- Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.cxx
- Tcl/SimVascular_2.0/Core/adapt.tcl
- Tcl/SimVascular_2.0/Core/osmsc.tcl
Changes to the adaptor and postsolver for old (ybar) and new (avg speed and pressure) solver output. Additional bug fixes in adaptor made as well.
> Adaptchanges

- Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.cxx
Very simple change within tetgen adaptor to approve quality of output tets
> DEV: Added higher quality requirements in tetgen adaptor

- Tcl/SimVascular_2.0/GUI/gui.tcl
tcl command no longer exists. Can convert opencascade or parasolid to polydata
> Bug in command to convert para to poly

- Tcl/SimVascular_2.0/Core/simvascular_load_shared_libs.tcl
just a double check for loading shared libs
> Load shared fix

- Code/SuperBuild/ITK.cmake
- Code/SuperBuild/OPENCASCADE.cmake
- Code/SuperBuild/TCL.cmake
- Code/SuperBuild/VTK.cmake
Making things consistent for an externals directory for superbuild
> one folder for externals

- Documentation/simvascular.Doxyfile.in
- Python/model/occt/nurbs_lofting.py
CMake var not changed with previous changes to CMake vars. Also, python function docs fixed to be above function
> DOC: Fixed cmake var in doc

- Tcl/SimVascular_2.0/simvascular_startup.tcl
Fix for startup. Build actually worked fine in mac after merge, but need fix for linux with lib extensions.
> BUG: Fixed the startup script for static tcl libs

- BuildWithMake/TestWithCMake/cmake-build-mac-distribution.sh
- BuildWithMake/TestWithCMake/cmake-build-mac-flowsolver-allexternals-relwdebinfo.sh
- BuildWithMake/TestWithCMake/cmake-build-mac-noflowsolver-allexternals-relwdebinfo.sh
- BuildWithMake/TestWithCMake/cmake-build-mac-parasolid-distribution.sh
DEV: Adds scripts for cmake configuration and compilation of the code.
Would like to move these to a different directory at some point, just wanted to get these in for now. Still need to make some on linux as well.
> Cmake build example

- Tcl/SimVascular_2.0/Core/sv.tcl
- Tcl/SimVascular_2.0/GUI/gui.tcl
- Tcl/SimVascular_2.0/GUI/model.tcl
The legacy files produced by SV3 for solid polydata models don't have mdf info.
> md5 check removed

- Externals/build-sv-externals-helper-wget-generic.sh
- Externals/build-sv-externals-linux.sh
minor update in path for src originals
> added toplevel script for linux in externals

- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_msi_helpers/makewxs-meshsim-and-parasolid.tcl
- BuildWithMake/Release/windows_msi_helpers/makewxs.tcl
- BuildWithMake/include.mk
- Tcl/SimVascular_2.0/simvascular_startup.tcl
updated installer scripts to generate Windows installer for SV including new SV3 code
fixed some bugs in meshsim/parasolid win32 installer due to lib rename a while back by Adam
> 2016 09 06 update win installer

- Code/Source/Modules/Mesh/files.cmake
- Code/Source/Modules/Mesh/svMesh.cxx
- Code/Source/Modules/Mesh/svMesh.h
- Code/Source/Modules/Mesh/svMitkMeshIO.cxx
- Code/Source/Modules/Mesh/svMitkMeshIO.h
- Code/Source/Modules/Mesh/svMitkMeshMapper2D.cxx
- Code/Source/Modules/Mesh/svMitkMeshMapper3D.cxx
- Code/Source/Modules/Mesh/svMitkMeshMapper3D.h
- Code/Source/Modules/Mesh/svMitkMeshObjectFactory.cxx
- Code/Source/Modules/Mesh/svMitkMeshObjectFactory.h
- Code/Source/Modules/Model/svModelDataInteractor.h
- Code/Source/Modules/Model/svModelElement.cxx
- Code/Source/Modules/Model/svModelElement.h
- Code/Source/Modules/Model/svModelUtils.cxx
- Code/Source/Modules/Model/svModelUtils.h
- Code/Source/Modules/Path/svPathLegacyIO.cxx
- Code/Source/Modules/ProjectManagement/svProjectManager.cxx
- Code/Source/Modules/Segmentation/svSegmentationLegacyIO.cxx
- Code/Source/Plugins/org.sv.gui.qt.meshing/files.cmake
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.h
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.ui
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svVtkMeshSphereWidget.cxx
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svVtkMeshSphereWidget.h
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.pathplanning/src/internal/svPathEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSegmentation2D.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSegmentationLegacyLoadAction.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSegmentationLegacyLoadAction.h
Improved Mesh 2D mapper to show inner mesh
Improve Segmentation IO for legacy format
MeshIO which store command history
GUI update with command history
interactively showing refining region set by users
> TetGen meshing plugin GUI completed

- Code/CMake/FindPYTHON.cmake
- Code/CMake/SimVascularExternals.cmake
- Code/CMake/SimVascularMacros.cmake
- Code/CMakeLists.txt
- Code/Scripts/CMakeLists.txt
- Code/Source/Modules/QtAppBase/CMakeLists.txt
- Code/Source/Modules/QtAppBase/svDisableGLHiDPI.h
- Code/Source/Modules/QtAppBase/svDisableGLHiDPI.mm
- Code/Source/Modules/QtAppBase/svDisplayEditor.cxx
- Code/Source/Modules/QtAppBase/svRenderWindowPart.cxx
- Externals/TestWithCMake/cmake-build-mac-flowsolver-allexternals-relwdebinfo.sh
- Externals/TestWithCMake/cmake-build-mac-noflowsolver-allexternals-relwdebinfo.sh
- Tcl/SimVascular_2.0/simvascular_startup.tcl
Has minimal build changes that will help in integrating with most recent workbench. Also contains the changes that were made for hiDPI on mac. These will get phased out with changes in workbench, so shouldn't be a big deal to include.
> 2016 10 25 build everything changes

- Externals/BuildHelpers/CompileScripts/post-install-mitk-linux.sh
BUILD: cleaning up post-install script for linux
> 2016-11-28-update_mitk_linux

- Code/Source/Modules/Common/svStringUtils.cxx
- Code/Source/Modules/Simulation/svSimulationUtils.cxx
- Code/Source/Modules/Simulation/svSimulationUtils.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/files.cmake
- Code/Source/Plugins/org.sv.gui.qt.simulation/plugin.xml
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svCapBCWidget.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPluginActivator.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPreferencePage.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPreferencePage.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPreferencePage.ui
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.ui
complete GUI for simulation including presolver, flowsolver, postsolver
use template file for solver.inp parameter in GUI
GUI for user to provide info about solvers
> complete plugin for Simulation

- Externals/TestWithCMake/cmake-build-linux-noflowsolver-use-existing-externals.sh
BUILD: changed path to Qt to /opt/Qt5.4.2
BUILD: added script to use existing externals
> 2016-12-11 build & test changes

- BuildWithMake/MakeHelpers/compiler.gcc.x64_linux.mk
- BuildWithMake/MakeHelpers/mitk-2016.03.x64_cygwin.mk
- BuildWithMake/MakeHelpers/mitk-2016.03.x64_linux.mk
- BuildWithMake/MakeHelpers/mitk-2016.03.x64_macosx.mk
- BuildWithMake/MakeHelpers/qt-5.4.x64_cygwin.mk
- BuildWithMake/MakeHelpers/qt-5.4.x64_linux.mk
- BuildWithMake/MakeHelpers/qt-5.4.x64_macosx.mk
- BuildWithMake/include.mk
- BuildWithMake/quick-build-linux.sh
- BuildWithMake/quick-build-macosx.sh
- BuildWithMake/quick-build-windows.sh
- BuildWithMake/targetlib.mk
- Code/Source/Modules/Makefile
- Code/Source/Plugins/org.sv.gui.qt.application/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.application/src/internal/svAboutDialog.cxx
- Code/Source/Plugins/org.sv.projectdatanodes/src/internal/Makefile
BUILD: updated make build for latest changes to master
> BUILD: 2016-12-12-welcome_screen

- BuildWithMake/MakeHelpers/meshsim-9.0-151017-vs12.x64_cygwin.mk
- BuildWithMake/MakeHelpers/meshsim-9.0-151017.x64_linux.mk
- BuildWithMake/include.mk
- Code/Source/Modules/Mesh/Makefile
- Code/Source/Modules/Model/Makefile
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.projectmanager/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/Makefile
BUILD: fixed building with parasolid and meshsim on linux/windows with make
> 2017-01-07-with-parasolid-meshsim

- Code/Source/Mesh/MMGMeshUtils/cv_mmg_mesh_utils.cxx
- Code/Source/Modules/Model/svModelElementPolyData.cxx
- Code/Source/Modules/Model/svModelUtils.cxx
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.h
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.ui
Added a subdivision of caps after model creation
Added estimate size button for model remeshing
Made mmg the mesher in both polydata remeshing if all faces are being remeshed
> DEV: Made a couple polydata changes for qt gui

- Code/Scripts/executable/install/simvascular-linux.in
- Code/Source/Plugins/org.sv.projectdatanodes/src/internal/svProjectDataNodesPluginActivator.cxx
- Code/Source/UI/main.cxx
BUG: Mac crash at end caused by cleanup in project datanodes, removed lines
DEV: Made tcl GUI default
DEV: Setup to start qt GUI if .simvascular_default_qt exists in home directory
> DEV: changes to prepare for mac installer

- BuildWithMake/Release/windows_installer_packages/wix-simvascular-bundle.wxs
- BuildWithMake/include.mk
- Code/Source/Modules/Mesh/Makefile
- Code/Source/Modules/Model/Makefile
- Code/Source/Modules/Model/svModelIO.cxx
- Code/Source/Modules/Model/svModelLegacyIO.cxx
- Code/Source/Modules/Model/svModelObjectFactory.cxx
- Code/Source/Modules/Model/svModelUtils.cxx
- Code/Source/Modules/Model/svModelUtils.h
- Code/Source/Modules/ProjectManagement/Makefile
- Code/Source/Modules/ProjectManagement/svProjectManager.cxx
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshCreate.cxx
- Code/Source/Plugins/org.sv.gui.qt.meshing/src/internal/svMeshEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelCreate.cxx
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/svModelLegacyLoadAction.cxx
- Code/Source/Plugins/org.sv.gui.qt.pathplanning/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/Makefile
- Code/Source/UI/main.cxx
DEV: updates to be able to build Windows release using make build
> 2017-01-18-release

- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_wrapper_scripts/sv.bat
BUG: still a couple more lines that needed to be merged for windows installer
> 2017-01-27-release

- Code/Source/Plugins/org.sv.gui.qt.simulation/files.cmake
- Code/Source/Plugins/org.sv.gui.qt.simulation/plugin.xml
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimJobStopAction.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimJobStopAction.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPluginActivator.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPreferencePage.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationPreferencePage.ui
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.ui
- Code/Source/Plugins/org.sv.projectdatanodes/src/internal/svProjectDataNodesPluginActivator.cxx
Find internal solvers for different operating systems
multi-threading for running solvers
> Improved Simulation Plugin

- Code/Source/Common/Geometry/cv_geom_init.cxx
- Code/Source/Common/Geometry/cv_sys_geom.cxx
- Code/Source/Common/Geometry/cv_sys_geom.h
- Code/Source/Modules/Model/svModelUtils.cxx
- Code/ThirdParty/vmtk/CMakeLists.txt
- Code/ThirdParty/vmtk/vtkvmtkCenterlineBifurcationReferenceSystems.cxx
- Code/ThirdParty/vmtk/vtkvmtkCenterlineBifurcationReferenceSystems.h
- Code/ThirdParty/vmtk/vtkvmtkMergeCenterlines.cxx
- Code/ThirdParty/vmtk/vtkvmtkMergeCenterlines.h
- Code/ThirdParty/vmtk/vtkvmtkPolyDataCenterlines.h
- Code/ThirdParty/vmtk/vtkvmtkReferenceSystemUtilities.cxx
- Code/ThirdParty/vmtk/vtkvmtkReferenceSystemUtilities.h
- Tcl/SimVascular_2.0/GUI/model.tcl
- Tcl/SimVascular_2.0/Plugins/polydata.tcl
Cleans surface prior to centerline extraction
Merges centerlines after extraction
Clean up of objects created in geom functions
> DEV: Changes to improve centerlines code

- BuildWithMake/Release/Makefile
- Code/Source/Plugins/org.sv.gui.qt.pathplanning/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/Makefile
- Code/ThirdParty/vmtk/Makefile
BUILD: added new files to Makefiles
> 2017-03-03 - added new filenames to makefile

- BuildWithMake/README-build-windows.txt
- BuildWithMake/quick-build-windows.sh
- Code/Source/Modules/Makefile
- Code/Source/Plugins/Makefile
BUG: cleaned up README, fixed bug in share-pre-build
> BUG: cleaned up README, fixed bug in share-pre-build

- BuildWithMake/Makefile
- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_msi_helpers/makewxs.tcl
- BuildWithMake/include.mk
- Code/Source/Model/MeshSimSolidModel/cvMeshSimSolidModel.h
- Code/Source/Model/MeshSimSolidModel/cv_meshsimsolid_init.h
- Code/Source/Modules/Model/Makefile
- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.pathplanning/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/Makefile
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/Makefile
- Code/Source/UI/main.cxx
- Tcl/SimVascular_2.0/simvascular_startup.tcl
BUILD: updates to create windows distribution for release using make build
> 2017-04-09-win-dist

- Code/CMake/SimVascularMacros.cmake
- Code/CMake/plugin_exports.h.in
Uses the exports configure file from ctk.
> BUG: Fixed exports for plugins to be same as those used by mitk

- Code/CMake/FindFREETYPE.cmake
- Code/CMake/FindMITK.cmake
- Code/Source/Common/Geometry/cv_integrate_surface.cxx
- Code/Source/Common/Geometry/cv_integrate_surface.h
- Code/Source/Modules/Segmentation/svContourGroup.cxx
- Code/Source/Modules/Segmentation/svSegmentationLegacyIO.cxx
- Code/Source/Modules/Simulation/CMakeLists.txt
- Code/Source/Modules/Simulation/svSimulationUtils.cxx
- Code/Source/Modules/Simulation/svSimulationUtils.h
- Code/Source/Plugins/org.sv.gui.qt.application/src/internal/svWorkbenchWindowAdvisor.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSegmentationLegacyLoadAction.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSegmentationLegacyLoadAction.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.cxx
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.h
- Code/Source/Plugins/org.sv.gui.qt.simulation/src/internal/svSimulationView.ui
Able to calculate flows in postprocessing
fix legacy groups importing issue
Able to build SV with sv_externals in Debug type
> Calculate flows for combo or multiple vtp/vtu files

- Code/Source/Modules/Segmentation/files.cmake
- Code/Source/Modules/Segmentation/svSegmentation3D.cxx
- Code/Source/Modules/Segmentation/svSegmentation3D.h
Created new svSegmentation3D file in modules and added collidingfronts function
> colliding fronts

- BuildWithMake/MakeHelpers/wix-3.11.x64_cygwin.mk
- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_msi_helpers/makewxs.tcl
- BuildWithMake/Release/windows_wrapper_scripts/sv.bat
DEV: added --ignore-pro flag to SV command-line
> Updated Release Build Options for win32 and Make

- Code/Source/Mesh/TetGenMeshObject/cvTetGenMeshObject.cxx
- Code/Source/Modules/Mesh/Common/svMeshTetGen.cxx
do not extract and copy in this case
> BUG: bug in meshing if only a surface mesh is desired

- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSeg2DEdit.cxx
- Code/Source/Plugins/org.sv.gui.qt.segmentation/src/internal/svSeg2DEdit.h
Think contextMenuAction was expecting a menu event, so weird things happened when menu didnt pop up.
Added simple single action menu for adding manual segmentations
> BUG: Fixed right click for manual addition of segmentations

- Code/Source/Plugins/org.sv.gui.qt.modeling/src/internal/Makefile
- Externals/ubuntu-14-prep.sh
- Externals/ubuntu-16-prep.sh
BUILD: adding new file from files.cmake to Makefile
> 2012-12-02-adding_files_to_makefile

- Code/Scripts/executable/developer/simvascular-linux.in
- Code/Scripts/executable/developer/simvascular-macos.in
- Code/Scripts/executable/install/simvascular-linux.in
- Code/Scripts/executable/install/simvascular-macos.in
- Code/Source/Application/main.cxx
Python shell setup is very similar to that found in vtk.
We can modify going forward, but this is basic shell setup.
No simvascular python modules loaded at this point, but should be easy to add
As a side note, this only makes the main messier, and we should clean up all of main sometime soon.
> DEV: Ability to create python shell if simvascular started in batch mode

- .travis.yml
- travis/travis_cmake_config.sh
- travis/travis_get_cmake_latest.sh
- travis/travis_get_qt.sh
- travis/travis_update_ubuntu.sh
DEV: trying to fix travis for make build
> 2018 06 20 fix travis make

- Code/Source/sv4gui/Modules/svFSI/sv4gui_MitksvFSIJobIO.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIJob.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui
displaying meshes for svfsi jobs
> Svfsi mesh fixes

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.application/resources/simvascular-activetab.qss
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.application/resources/simvascular.qss
@osmsc maybe try building before merging. Makes a style and color change to the top toolbar. I think it looks better than the grey toolbar, but should probably have somebody else's opinion involved as well.
> DEV: Updating style for top toolbar

- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIJob.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIeqClass.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui
discovered the svfsi plugin was outputting "default" as a precondition causing the solver to not run.
> svfsi plugin fixes to default preconditioner

- Code/Scripts/CMakeLists.txt
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.imageprocessing/sv4gui_ImageProcessing.ui
This fixes issues with the imageprocessing plugin ui with different screen widths
> Imageprocessing ui fixes

- Code/CMake/Externals/HDF5.cmake
- Code/Scripts/CMakeLists.txt
- Distribution/CMakeLists.txt
- Distribution/qt.conf
- Distribution/qt_ext.conf
Hey,
Here are the fixes to make installed SimVascular work on ubuntu.
Had to add QTWEBENGINEPROCESS_PATH to the simvascular launcher script and a qt.conf file to the simvascular binary location and also one for the svExternals.
> Qtwebengine ubuntu

- BuildWithMake/README-build-windows.txt
- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_msi_helpers/makewxs.tcl
- BuildWithMake/Release/windows_wrapper_scripts/sv.bat
- BuildWithMake/quick-build-windows.sh
DEV: updated windows installer build to handle changes to our .exe and make sure that it doesn't require a pre-installed  version of Qt
> 2018-11-24-RC1

- README.md
This would have saved me about 5-7 hours of stressful work today. I didn't even know there were two "installation options..."
> adding clear instruction to TWO different documentation bases

- BuildWithMake/Release/Makefile
- BuildWithMake/Release/developer_wrapper_scripts/developer-core-script
- BuildWithMake/Release/developer_wrapper_scripts/developer-simvascular-script
- BuildWithMake/Release/windows_msi_helpers/makewxs.tcl
- Code/Source/Application/main.cxx
- Code/Source/Application/svTcl_AppInit.cxx
- Code/Source/Application/sv_use_win32_registry.cxx
- Code/Source/Application/sv_use_win32_registry.h
- Tcl/SimVascular_2.0/GUI/gui.tcl
- Tcl/SimVascular_2.0/simvascular_startup.tcl
DEV: updates to read plugin info from registry on win32
> 2019-01-20-win32-reg

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.pathplanning/sv4gui_PathEdit.cxx
The image was being reset every time a new path was being created. See Issue #404.
> Comment out image reset code.

- BuildWithMake/Release/Makefile
- BuildWithMake/Release/windows_wrapper_scripts/sv.bat
- BuildWithMake/quick-build-windows.sh
- Externals/Make/2018.05/BuildHelpers/CompileScripts/post-install-python-windows.sh
- Tcl/SimVascular_2.0/Core/sv.tcl
- Tcl/SimVascular_2.0/simvascular_startup.tcl
DEV: some minor changes to tcl launch script and for jupyter notebook wrappers
DEV: updated to more recent externals build in make quick build script for windows
> 2019-02-25-stanford

- .travis.yml
- travis/travis_update_ubuntu.sh
BUILD: updating from trusty -> xenial (ubuntu 16.04)
> 2019-03-10-xenial

- Code/CMake/PrepareTcl.cmake
- Code/Scripts/CMakeLists.txt
- Distribution/CMakeLists.txt
DEV: needed to copy the sv and sv_vis python site-packages into the installer when using cmake
DEV:  hacking hdf5 check in tensorflow to use our version for now
> 2019-03-17-linux_installer

- Externals/Make/2019.02/BuildHelpers/CompileScripts/post-install-python-linux.sh
- Externals/Prep/2019.02/ubuntu-18-prep.sh
- Externals/README-build-externals.txt
DEV: updated prep scripts for ubuntu 18 to build externals
> 2019-03-31-ubuntu18

- Code/Source/sv4gui/Modules/Simulation1d/python/generate_1d_mesh.py
- Code/Source/sv4gui/Modules/Simulation1d/python/mesh.py
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPython1d.cxx
I've fixed some problems with reporting errors in the python script.
@osmsc We should merge this and create new installers so users can identify problems  generating the solver input file.
> 1d simulation plugin crash

- Code/CMake/Externals/VTK.cmake
- Code/CMake/SimVascularConfig.cmake.in
- Code/Source/sv/Mesh/AdaptObject/sv_AdaptObject.cxx
- Code/Source/sv/Model/PolyDataSolidModel/sv_PolyDataSolid.h
DEV: selected changes from pull request 441
> 2019-05-02 commits from pull request 441

- Code/Source/sv4gui/Modules/MachineLearning/sv4gui_MLUtils.cxx
- Python/site-packages/sv_ml/components/models/nn.py
- Python/site-packages/sv_ml/sv_wrapper.py
Changes we discussed in the meeting.
Also noticed some filepath manipulations that were unix style, which I now made universal.
> fixing python interpreter and making paths os independent

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.ui
I commented out a lot of GUI code that is not currently implemented but may want to add it in later. This guy still needs a lot of work.
> Simplify gui and make widgets resize.

- BuildWithMake/Makefile
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.ui
DEV: fixing bugs in 2-D segmentation window, adding tabs
> 2019-06-02

- BuildWithMake/quick-build-linux.sh
DEV: updated externals version for quick build on centos
> 2019-06-03-update_quick_build_centos

- BuildWithMake/README-build-macosx.txt
BUILD: updated readme for make build on macos
> 2019-06-03 update readme for macos

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferencePage.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferencePage.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferencePage.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferences.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_MPIPreferences.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationPreferencePage.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationPreferencePage.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationPreferencePage.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.ui
I've modified the GUI a bit, fixed some problems setting mpiexec and detecting mpi implementation, added warning messages and added widget documentation. 
I also added a 'use mpi' checkbox to the Simulation panel.
> Incompatible simulation preferences being discovered 493

- Code/CMake/SimVascularDependentOptions.cmake
- Code/Scripts/executable/developer/simvascular-windows.in
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/files.cmake
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationPreferences.cxx
BUG: fixed cmake build for win32
> 2019-06-14-cmake_build_windows

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPython1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.ui
- Python/site-packages/sv_1d_simulation/generate_1d_mesh.py
- Python/site-packages/sv_1d_simulation/mesh.py
- Python/site-packages/sv_1d_simulation/parameters.py
I've add a linear material model as requested by Melody Dong, also modified some default parameter values.
> Add linear material model, adjust default material parameters.

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.ui
We need to test this on Windows.
> Adjust gui layouts so panel resizes.

- Externals/Make/2019.06/BuildHelpers/CompileScripts/sed-script-x64_cygwin-options-cl.sh
- Externals/Make/2019.06/BuildHelpers/Scripts/superbuild-linux-gcc.sh
- Externals/Make/2019.06/BuildHelpers/Scripts/superbuild-mac_osx-clang.sh
- Externals/Make/2019.06/BuildHelpers/Scripts/superbuild-windows-cl.sh
- Externals/Make/2019.06/BuildHelpers/Scripts/untar-unzip-source-all.sh
- Externals/Patches/2019.06/patch-mitk-2018.04.2-sv_externals.patch
BUILD: some updates to 2019.06 externals build
> 2019-07-02-externals

- Code/Source/sv4gui/Plugins/org.sv.pythondatanodes/sv4gui_Vis_init_py.cxx
Added Python functions to remove data node from GUI. Fixed MITK fatal error message when using Python GUI without an open project.
> MAINT: 2019 07 29 Python Bug Fix

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/files.cmake
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPythonConvert1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPythonConvert1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.ui
- Python/.gitignore
- Python/site-packages/sv_1d_extract_results/__init__.py
- Python/site-packages/sv_1d_extract_results/extract_results.py
- Python/site-packages/sv_1d_extract_results/graphics.py
- Python/site-packages/sv_1d_extract_results/manage.py
- Python/site-packages/sv_1d_extract_results/node.py
- Python/site-packages/sv_1d_extract_results/parameters.py
- Python/site-packages/sv_1d_extract_results/segment.py
- Python/site-packages/sv_1d_extract_results/solver.py
Here are some changes implementing converting 1D simulation results (.dat) to CSV format files. The changes are to the 1D Simulation plugin GUI and code to execute a Python script to convert the files. I also added a new package to the Python/site-packages.
> Sv 1d extract results - Issue #583

- Python/site-packages/sv_ml/modules/layers.py
copyright notice for layers.py
> adding copyright notice back to layers.py

- CMakeLists.txt
- Code/CMake/SimVascularTclSetup.cmake
- Code/CMakeLists.txt
- Externals/CMakeLists.txt
DEV: removing old cmake commands
> 2019-11-29

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/Makefile
BUILD: added in covert1d files into make build
> 2020-04-06 updated make build for 1d plugin

- Python/site-packages/sv_1d_extract_results/solver.py
Add a correct counter when converting 1D simulation results.
> Add correct counter.

- Code/Source/sv4gui/Modules/MachineLearning/sv4gui_MachineLearningUtils.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
- Python/site-packages/sv/__init__.py
- Python/site-packages/sv_ml/README.md
- Python/site-packages/sv_ml/modules/vascular_data.py
- Python/site-packages/sv_ml/sv_wrapper.py
Comments and readme for the SV Machine Learning code.
> Documentation for SV Machine Learning Code

- Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx
- Code/ThirdParty/vmtk/simvascular_vmtk/vtkvmtkPolyDataCenterlineSections.cxx
- Code/ThirdParty/vmtk/simvascular_vmtk/vtkvmtkPolyDataCenterlineSections.h
> Add CenterlineId to centerline geometry

- Python/site-packages/sv_1d_simulation/io.py
- Python/site-packages/sv_1d_simulation/mesh.py
> Add upstream junction to 1D branch length

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.h
I also modified the code to not create node if segmentation fails.
> Fix sv crashing if no segmentation is computed

- Code/Source/PythonAPI/SegmentationSeries_PyClass.cxx
- Code/Source/PythonAPI/Segmentation_PyClass.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourCircle.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourEllipse.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourPolygon.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourSplinePolygon.cxx
The contour kernel types were not being set in SV. Also remove getting control points for the Segmentation class.
> Fix a problem with setting the sv contour kernel type.

- Code/Source/sv4gui/Modules/Simulation1d/sv4gui_MitkSimJobIO1d.cxx
- Code/Source/sv4gui/Modules/Simulation1d/sv4gui_SimJob1d.cxx
- Code/Source/sv4gui/Modules/Simulation1d/sv4gui_SimJob1d.h
- Code/Source/sv4gui/Modules/Simulation1d/sv4gui_SimulationUtils1d.cxx
- Code/Source/sv4gui/Modules/Simulation1d/sv4gui_SimulationUtils1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_CapBCWidget1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_CapBCWidget1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_CapBCWidget1d.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPython1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationPython1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_SimulationView1d.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation1d/sv4gui_TableCapDelegate1d.cxx
- Python/site-packages/sv_1d_simulation/generate_1d_mesh.py
Add a couple of new meshing parameters and  coronary BC.
> 1d simulation g UI 657

- Code/Source/Application/SimVascular_Init_py.cxx
- Code/Source/PythonAPI/CMakeLists.txt
- Code/Source/PythonAPI/ImagingImage_PyClass.cxx
- Code/Source/PythonAPI/Imaging_PyModule.cxx
- Code/Source/PythonAPI/Imaging_PyModule.h
- Code/Source/sv3/Segmentation/sv3_SegmentationUtils.cxx
- Code/Source/sv3/Segmentation/sv3_SegmentationUtils.h
- Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_Contour.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.projectmanager/sv4gui_ProjectAddImageAction.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
- Python/site-packages/sv/__init__.py
The `Image` class is not complete but it is still useful. Do a `help(sv.imaging)` to see its methods.
> Python api interface reading image 812

- Code/Source/PythonAPI/ImagingImage_PyClass.cxx
- Code/Source/PythonAPI/Makefile
Updating Make build & fixing bug on Windows to write out mitk image and transform file from the command line
> 2021-03-15-pythonimg

- Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.cxx
- Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.h
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.application/sv4gui_FileOpenProjectAction.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.projectmanager/sv4gui_ProjectAddImageAction.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.projectmanager/sv4gui_ProjectAddImageAction.h
I need to merge this so I can complete https://github.com/SimVascular/SimVascular/issues/815.
> Remove svproj file 821

- Python/site-packages/sv_1d_extract_results/extract_results.py
- Python/site-packages/sv_1d_extract_results/parameters.py
- Python/site-packages/sv_1d_extract_results/post.py
- Python/site-packages/sv_1d_extract_results/vtk_functions.py
- Python/site-packages/sv_1d_simulation/generate_1d_mesh.py
Adds Python functions for #817 that are connected to the GUI (#830).
> Add 1D post-processing functions

- Python/site-packages/sv_1d_simulation/io_0d.py
- Python/site-packages/sv_1d_simulation/io_headers.py
- Python/site-packages/sv_1d_simulation/parameters.py
> Add 0d solver options to input file

- Code/Source/PythonAPI/SimulationOneDimensional_PyClass.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.cxx
- Externals/Make/2019.06/BuildHelpers/CompileScripts/post-install-python-linux.sh
- Externals/Make/2019.06/BuildHelpers/CompileScripts/post-install-python-mac_osx.sh
- Externals/Make/2019.06/BuildHelpers/CompileScripts/post-install-python-windows.sh
- Python/site-packages/sv_1d_extract_results/extract_results.py
- Python/site-packages/sv_1d_extract_results/parameters.py
- Python/site-packages/sv_1d_extract_results/post.py
- Python/site-packages/sv_1d_extract_results/solver.py
- Python/site-packages/sv_1d_extract_results/vtk_functions.py
- Python/site-packages/sv_1d_simulation/io_0d.py
- Python/site-packages/sv_1d_simulation/models.py
- Python/site-packages/sv_1d_simulation/parameters.py
> 0d post processing 845

- Code/Source/sv4gui/Modules/svFSI/files.cmake
- Code/Source/sv4gui/Modules/svFSI/sv4gui_MitksvFSIJob.h
- Code/Source/sv4gui/Modules/svFSI/sv4gui_MitksvFSIJobIO.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIJob.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIJob.h
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIbcClass.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIbcClass.h
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIeqClass.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSIeqClass.h
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSViscosity.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_svFSViscosity.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui.1
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.svfsi/sv4gui_svFSIView.ui.2
I've added a minimum of new GUI components so the plugin can write a valid simulation input file.
> Update svfsi plugin 592

- Python/site-packages/sv_rom_extract_results/post.py
- Python/site-packages/sv_rom_extract_results/solver.py
> Use 0d branch post-processing

- Code/Source/PythonAPI/SimulationROM_PyClass.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.h
> add model order to input file and results

- Code/Source/PythonAPI/SimulationROM_PyClass.cxx
> fix make build

- .gitmodules
- BuildWithMake/Makefile
- CMakeLists.txt
- Code/CMake/SimVascularOptions.cmake
- Code/CMakeLists.txt
BUILD: trying to fix clone of zerodsolver code in cmake and make
> 2021-06-11 trying to fix zerodsolver clone request

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPython.h
> change 0d solver input file name

- Code/CMakeLists.txt
Still trying to fix submodule call
> BUILD: fixing submodule check for CMake

- Code/Source/PythonAPI/SimulationROM_PyClass.cxx
> fix switch between 0d/1d solver file

- Code/Source/PythonAPI/MeshingAdaptive_PyClass.cxx
- Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx
- Code/Source/sv2/Segmentation/sv2_LevelSetSparseGrid.cxx
- Code/Source/sv2/Segmentation/sv2_StateArray.h
- Code/Source/sv3/ITKSegmentation/sv3_ITKLevelSetBase.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPython.cxx
Some functions were not returning a value for a non-void function.
> Add return values.

- Code/ThirdParty/vmtk/simvascular_vmtk/vtkvmtkPolyDataCenterlineSections.cxx
> delete bifurcation points inside branches

- Python/site-packages/sv_rom_simulation/io_0d.py
- Python/site-packages/sv_rom_simulation/io_1d.py
- Python/site-packages/sv_rom_simulation/mesh.py
- Python/site-packages/sv_rom_simulation/models.py
> Use json input files for 0D

- .travis.yml
> Deactivate Mac OS build testing on Travis

- Code/Source/sv/Model/PolyDataSolidModel/sv_PolyDataSolid.cxx
- Code/Source/sv4gui/Modules/ProjectManagement/sv4gui_ProjectManager.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourModelThresholdInteractor.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourModelThresholdInteractor.h
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.projectmanager/sv4gui_ProjectAddImageAction.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
This is a fix for image-based threshold and level set segmentation of DICOM with transformed axes.
> Image based segmentation does not work 923

- Code/Source/sv/Mesh/TetGenMeshObject/sv_TetGenMeshObject.cxx
- Code/Source/sv/Mesh/TetGenMeshObject/sv_TetGenMeshObject.h
- Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx
This is the fix for boundary layer cap meshing that produced cap meshes that were not flat.
> TetGen boundary layer meshes not flat caps 931

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPythonConvert.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.cxx
I've put back the original code to convert results using the CPython API calls.
> Add back converting results using CPython API.

- Code/Source/PythonAPI/Geometry_PyModule.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/Makefile
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ConvertWorkerROM.h
* adding in missing source file in Makefile for romsimulation
* removing whitespace at end of line in pymodule
> 2022-02-09: BUG: fixing bugs to build on windows:

- Code/Source/sv/Mesh/TetGenMeshObject/sv_TetGenMeshObject.cxx
See https://github.com/SimVascular/SimVascular/issues/672.
> Add resetting face IDs for locally refined regions.

- Code/Source/PythonAPI/ModelingPolyData_PyClass.cxx
- Code/Source/PythonAPI/PyUtils.cxx
- Code/Source/PythonAPI/PyUtils.h
- Code/Source/PythonAPI/Vmtk_PyModule.cxx
Add the `sv.modeling.PolyData.compute_centerlines` method.
> Python api add model compute centerlines

- Python/site-packages/sv_rom_simulation/io_0d.py
Closes #1019. Bug found on [SimTK](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=188&t=17441&p=48513&start=0&view=).
Works with latest `svZeroDSolver` https://github.com/SimVascular/svZeroDSolver/commit/46e08d6613c9660f425db37d1413610934ea1537
None
Extracted a 0D model from DemoProject. `NORMAL_JUNCTION` appears for both junctions with one or more outlets.
> Adapt svZeroDSolver to 46e08d6

- Code/Source/PythonAPI/MeshingMesher_PyClass.cxx
- Code/Source/PythonAPI/MeshingTetGenOptions_PyClass.cxx
- Code/Source/sv/Mesh/TetGenMeshObject/sv_tetgenmesh_utils.cxx
The Python API Meshing.get_face() method was not returning PolyData with face ID, normals and region ID VTK data arrays. See https://github.com/SimVascular/SimVascular/issues/1049.
> Create mesh complete folder python 1049

- LICENSE.md
Move and rename the license file.
> Move license file.

- Code/Source/sv4gui/Modules/svFSI/sv4gui_XmlWriter.cxx
- Code/Source/sv4gui/Modules/svFSI/sv4gui_XmlWriter.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPreferencePage.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationPreferencePage.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.romsimulation/sv4gui_ROMSimulationView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
It seems that the initial merge missed some things, Qt string problems and some old tinyxml2 includes.
I fixed these and SV now builds and runs on MacOS.
> Fix tinyxml2 includes and Qt problems.

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_CapBCWidget.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_TableCapDelegate.cxx
> Remove coronary bc option.

- Code/Source/PythonAPI/MeshingTetGenOptions_PyClass.cxx
- Code/Source/sv/Geometry/sv_sys_geom.cxx
- Code/Source/sv/Utils/sv_vtk_utils.cxx
- Code/Source/sv4gui/Modules/Model/Common/sv4gui_ModelUtils.cxx
- Code/Source/sv4gui/Modules/QtWidgets/sv4gui_ResliceSlider.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_ContourGroupIO.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_MitkSeg3DIO.cxx
- Code/Source/sv4gui/Modules/Segmentation/sv4gui_SegmentationUtils.cxx
- Code/Source/sv4gui/Modules/Simulation/sv4gui_SimXmlWriter.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.modeling/sv4gui_ModelEdit.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_ContourGroupCreate.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_LoftParamWidget.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_LoftingUtils.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/resources/solvertemplate.xml
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx
- Code/Source/vtkSV/Modules/Boolean/vtkSVLoopBooleanPolyDataFilter.cxx
I've fixed some bugs and added some new solver parameters.
> Some bug fixes

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SolverProcessHandler.cxx
I've updated the code to display simulation status.
> Update parsing history for simulation status, add terminate process.

- Code/Source/sv/Mesh/MMGMeshUtils/sv_mmg_mesh_utils.cxx
- Code/Source/sv/Mesh/VMTKUtils/sv_vmtk_utils.cxx
- Code/Source/sv/Utils/sv_vtk_utils.cxx
- Code/Source/sv/Utils/sv_vtk_utils.h
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.meshing/sv4gui_MeshEdit.cxx
- Code/Source/vtkSV/Common/vtkSVGeneralUtils.cxx
- Code/Source/vtkSV/Modules/Segmentation/vtkSVCenterlineGraph.cxx
I've fixed boundary layer meshing and have resolved several other unimplemented threshold changes.
> Fix boundary layer meshing bug 

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.pathplanning/sv4gui_PathEdit.cxx
Disable some debugging statements.
> Disable some debugging statements.

- Code/Source/sv4gui/Plugins/org.sv.gui.qt.segmentation/sv4gui_Seg2DEdit.ui
The machine learning segmentation can be run from the multipath panel so disable it for now.
> Disable the segmentation multipath panel used for machine learning.

- Code/Source/sv4gui/Modules/Simulation/sv4gui_SimXmlWriter.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_CapBCWidget.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_CapBCWidget.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.cxx
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_SimulationView.ui
- Code/Source/sv4gui/Plugins/org.sv.gui.qt.simulation/sv4gui_TableCapDelegate.cxx
This was a branch to add writing averaged output at surface faces but also includes fixes to a couple of bugs I found.
> Cfd simulation add volume and boundary integral output 1128
